### ISSUE TITLE
Issue with signing up

### ISSUE THREAD

**Issue by trace2798** [vanxh/openbio#29]
I tried to sign up with Github and got the following
![image](https://github.com/vanxh/openbio/assets/113078518/145d72be-5749-46ac-809e-42f774618614)

**Comment by vanxh** [comment]
Hey, sorry for the issue. Can you try it again?

**Comment by trace2798** [comment]
Hey. It happened again with Github but worked fine with Google.

**Comment by trace2798** [comment]
Also after getting logged in this is the first thing I saw. Possibly a bug somewhere. Once I refreshed the page, everything worked fine
![image](https://github.com/vanxh/openbio/assets/113078518/7437be5d-ee81-4344-9479-43343231cdaa)

**Comment by vanxh** [comment]
Ill have a look
