### ISSUE TITLE
Error while logging In with github 

### ISSUE THREAD

**Issue by tiwariParth** [vanxh/openbio#7]
Hello maintainers, I am getting error while attempting to logging In with github account its authorizing it tho. But after that its showing the following error.
![Screenshot from 2023-09-04 20-23-49](https://github.com/vanxh/openbio/assets/99398053/ca1dd6fa-1845-4ebd-bbc9-85f109ddf68c)

**Comment by vanxh** [comment]
Hey @tiwariParth sorry for any inconvenience caused. I just tested out signing up with github it worked for me could you test it again and let me know?
